feat:  Setting of Routes Skeletons[REST API](#39523)
nxfareed/javascript-server pull request #10
Opened 2020-01-31 13:34 UTC by nxfareed

Link for todays task: https://redmine.successive.tech/issues/39523

2020-02-06 07:57 UTC, Prabal555 requested changes

2020-02-06 07:57 UTC, Prabal555 commented on src/controllers/trainee/routes.ts
> +.delete( traineeController.delete);
destructure the values at the top

2020-02-06 07:57 UTC, Prabal555 commented on src/controllers/trainee/controller.ts
> +import { Request, Response } from 'express';
Indentation in the file

2020-02-06 07:57 UTC, Prabal555 commented on src/controllers/trainee/routes.ts
> +.delete( traineeController.delete);
indentation is also not correct

2020-02-06 07:57 UTC, Prabal555 commented on tsconfig.json
>          "target": "es6",
conflicts have been pushed

2020-02-06 07:57 UTC, Prabal555 commented on tsconfig.json
> +=======
Indentation is missing

2020-02-06 14:05 UTC, Prabal555 requested changes

2020-02-06 14:05 UTC, Prabal555 commented on src/Server.ts
> +            app.use(errorHandler);
indentation is not correct

2020-02-06 14:05 UTC, Prabal555 commented on src/controllers/trainee/validation.ts
> +    {
indentation

2020-02-06 15:35 UTC, Prabal555 requested changes

2020-02-06 15:35 UTC, Prabal555 commented on src/controllers/trainee/validation.ts
> +        },
not complete

2020-02-06 15:35 UTC, Prabal555 commented on src/controllers/trainee/validation.ts
> +            },
code incomplete

2020-02-07 09:12 UTC, nxfareed commented on src/controllers/trainee/validation.ts
> +            },
This has been left blank for the time when we have to add a  particular custom operation when required.

2020-02-07 09:16 UTC, merged