feat:Generic Routes Validations(#39524)
nxfareed/javascript-server pull request #11
Opened 2020-02-06 15:32 UTC by nxfareed

2020-02-07 09:41 UTC, nxfareed commented
Link for the day's task: https://redmine.successive.tech/issues/39524

2020-02-11 14:00 UTC, Prabal555 requested changes

2020-02-11 14:00 UTC, Prabal555 commented on package.json
> +    "body-parser": "^1.19.0",
should not be in the devDependencies

2020-02-11 14:00 UTC, Prabal555 commented on src/controllers/trainee/routes.ts
> +    .delete(validationChecker(validation.delete), det)
we can use destructuring for validation as well

2020-02-11 14:00 UTC, merged